### ISSUE TITLE
update from ggml to gguf

### ISSUE THREAD

**Issue by amaiya** [amaiya/onprem#1]
New model: https://huggingface.co/TheBloke/Yarn-Llama-2-7B-64K-GGUF

**Comment by rabilrbl** [comment]
@amaiya Is there any special bindings for GGML format in the project?

Just by updating `llama-cpp-python` to latest version should work right?

**Comment by amaiya** [comment]
@rabilrbl No, there are no special bindings.  Updating `llama-cpp-python` should work (as long as you don't use the default GGML models and supply the URL to a GGUF model).

**Comment by amaiya** [comment]
https://huggingface.co/TheBloke/WizardLM-13B-V1.2-GGUF
