### ISSUE TITLE
Ingest .csv?

### ISSUE THREAD

**Issue by VikR0001** [amaiya/onprem#15]
Does `ingest` understand .csv format? I provided a .csv file with:

```
    from onprem import LLM
    llm = LLM()
    llm.ingest('/Users/mypath/myfile.csv')
```

I asked a question with this code:

```
    question = """
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
[my instructions]

### Response:

   """
       answer, docs = llm.ask(question)
```

I got this message:

> ValueError: A vector database has not yet been created. Please call the LLM.ingest method.

Does ingest understand .csv files yet?

**Comment by amaiya** [comment]
Yes, CSVs are supported and work as expected.  Your error is occurring because the `ingest` method accepts a folder of one or more files (not the path to a single file).  

Try this and it should work:
```python
llm.ingest('/Users/mypath/folder_with_csv/mfile.csv`)
```

I have added  a check to ensure that the argument to `ingest` is a folder not a file.
