### ISSUE TITLE
Talk to Your Documents with Retrieval-Augmented Generation not working

### ISSUE THREAD

**Issue by Velcin** [amaiya/onprem#25]
Hi,

I've tested the "talk to your document feature" via the notebook demo (OnPrem.LLM-QuickStart.ipynb) but it doesn't work. It seems to be during the data "ingestion".

Here is the error I get:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-36d6989666c4>](https://4k3n7griuzk-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20230919-060142_RC00_566594702#) in <cell line: 1>()
----> 1 llm.ingest('/tmp/sample_data')

14 frames
[/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py](https://4k3n7griuzk-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20230919-060142_RC00_566594702#) in <module>
     55 IS_PYSTON = hasattr(sys, "pyston_version_info")
     56 HAS_REFCOUNT = getattr(sys, 'getrefcount', None) is not None and not IS_PYSTON
---> 57 HAS_LAPACK64 = numpy.linalg._umath_linalg._ilp64
     58 
     59 _OLD_PROMOTION = lambda: np._get_promotion_state() == 'legacy'

AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'

UPDATE:
I've tested the solution given in https://github.com/amaiya/onprem/issues/4 but it solved the problem for the local .py version, and it's too long with no GPU. Therefore I'm still in trouble with the Jupiter notebook version.

Thank you
Julien

**Comment by amaiya** [comment]
Hello,

I just tested the [Google Colab notebook](https://colab.research.google.com/drive/1LVeacsQ9dmE1BVzwR3eTLukpeRIMmUqi?usp=sharing) to which you are referring and everything worked perfectly.  If you downloaded the notebook and running it locally, it may be a problem with your numpy installation.  See [this post](https://github.com/deeppavlov/DeepPavlov/issues/1460#issuecomment-1094190974) for a fix (which involves uninstalling and reinstalling numpy).

**Comment by amaiya** [comment]
Also, if you're running the notebook within Google Colab with a GPU, please make sure you restart the notebook, as instructed in the notebook.  Feel free to respond to this thread with further questions.

**Comment by Velcin** [comment]
You're perfectly right. I didn't understand that I must restart the environment, I guess it's because it sounds weird. But all is ok now, sorry for spending your time.
Julien
