### ISSUE TITLE
ValidationError: 1 validation error for LlamaCpp

### ISSUE THREAD

**Issue by Jacob-Langley** [amaiya/onprem#37]
It appears to download wizardlm-13b-v1.2.Q4_K_M.gguf without issue, but then gives the below when I try to use LLM().

Same for the 7B

llm = LLM(use_larger=True, n_gpu_layers=35)
Traceback (most recent call last):

  Cell In[4], line 1
    llm = LLM(use_larger=True, n_gpu_layers=35)

  File ~\anaconda3\lib\site-packages\onprem\core.py:119 in __init__
    self.load_llm()

  File ~\anaconda3\lib\site-packages\onprem\core.py:226 in load_llm
    self.llm = llm = LlamaCpp(

  File ~\anaconda3\lib\site-packages\langchain\load\serializable.py:74 in __init__
    super().__init__(**kwargs)

  File pydantic\main.py:341 in pydantic.main.BaseModel.__init__

ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: C:\Users\jlangley\onprem_data\wizardlm-13b-v1.2.Q4_K_M.gguf. Received error fileno (type=value_error)

**Comment by amaiya** [comment]
What  version of `llama-cpp-python` are you using?

Does the error still occur if you supply `verbose=True` to `LLM`?

```python
llm = LLM(use_larger=True, n_gpu_layers=35, verbose=True)
```

**Comment by Jacob-Langley** [comment]
verbose=True appears to have done the trick! -- (why?)

**Comment by amaiya** [comment]
Due to what seems to be [a bug in llama-cpp-python](https://github.com/abetlen/llama-cpp-python/issues/796).
