### ISSUE TITLE
Number of tokens

### ISSUE THREAD

**Issue by lysa324** [amaiya/onprem#38]
what is the maximum number of tokens the framework can accept as model inputs? does this number depend on the WizardLM model or OnPrem.LM?

**Comment by amaiya** [comment]
This depends on the model you use with OnPrem.LLM.  The [default context window size is set to `n_ctx=2048`](https://amaiya.github.io/onprem/core.html#llm) in OnPrem.LLM, but you can increase it if you use models that accept larger context windows.

**Comment by lysa324** [comment]
good morning, 
thank you for answering! i would like to understand how the model has the ability to read multiple pdf's from the sample_data folder when the maximum accepted token is 2048? 

thanks

**Comment by amaiya** [comment]
See the [Retrieval Augmented Generation (RAG) paper](https://arxiv.org/abs/2005.11401) for details.
