### ISSUE TITLE
Unable to get ingest working

### ISSUE THREAD

**Issue by smach** [amaiya/onprem#4]
This very well may be my fault, since my Python knowledge is rather basic. But when trying to follow the ingest document examples with my own documents using the code

    from onprem import LLM
    llm = LLM()
    llm.ingest('./sample_docs/')`

I get the error below

    RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

This happens both on my Mac and on my Windows PC.

Below code works fine, though.

    prompt = """What is a large language model?"""
    llm_response = llm.prompt(prompt)

**Comment by amaiya** [comment]
Hi @smach:  

The call to `ingest` [in this Google Colab notebook](https://colab.research.google.com/drive/1LVeacsQ9dmE1BVzwR3eTLukpeRIMmUqi?usp=sharing) seems to work fine and all CI tests pass including ones with `ingest`.

That error usually indicates that you need to place code in a `if __name__ == '__main__':` guard (as mentioned in [this post](https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing)).    

Are you running this in a Jupyter notebook?  Or, are you putting the code in a `.py` file and running it?    If the latter, perhaps you may need to do this:

```python
if __name__ == '__main__':    
    from onprem import LLM
    llm = LLM()
    llm.ingest('./sample_docs/')`
```

**Comment by smach** [comment]
Thank you, I am indeed running it in a local .py file, and that stops the error. (I'm now having problems with the correct version of pymupdf which probably has nothing to do with this package. I suspect I need to improve my knowledge of Python sysadmin and then try again sometime.)
