### ISSUE TITLE
feat: Add optional argument to specify custom path to download LLM

### ISSUE THREAD

**Issue by rabilrbl** [amaiya/onprem#5]
Currently there is no implementation to specify custom path location to download a model.

By default, the model is downloaded at `~/onprem_data`

Example:

```py
from onprem import LLM

llm = LLM(model_download_path="~/models")
# or
llm.download_model(model_download_path="~/models")
```

**Comment by rabilrbl** [comment]
@amaiya I am ready to make PR for this. Shall I proceed?

**Comment by amaiya** [comment]
Hi @rabilrbl I should probably create a `CONTRIBUTING.md` at some point, but I'll mention this information here. Are you familiar with the [nbdev](https://github.com/fastai/nbdev) project?

This project was built using [nbdev](https://github.com/fastai/nbdev). As a result, all development is done within the notebooks in the `nbs` folder.  The `.py` files are auto-generated from the notebooks (which is noted in an auto-generated message at the top of the `.py` files).

You can take a look at [this tutorial](https://nbdev.fast.ai/tutorials/tutorial.html) to learn more about building and contributing to projects that use nbdev.

Adding a `model_download_path` parameter sounds good as long as the default for the parameter is `None` in which case `LLM` will work exactly as it does now (i.e., store model in `~/onprem_data`.

Thanks!

**Comment by rabilrbl** [comment]
@amaiya Got it. I'll try to modify `.ipynb` files for the PR.

the `model_download_path` will be `Option[str]=None` when not present It will work exactly the same as before.
